### ISSUE TITLE
Dart 2.0 problem

### ISSUE THREAD

**Issue by ebesirik** [dart-league/validators#3]
When I try to get packages, I get this error;
`The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because ***** depends on validator any which requires SDK version <2.0.0, version solving failed.

pub get failed (1)`

**Comment by luisvt** [comment]
you need to specify the version to `^1.0.0` in your `pubspec.yaml` file:

```yaml
dependencies:
  validators: ^1.0.0
```

**Comment by willladislaw** [comment]
> you need to specify the version to `^1.0.0` in your `pubspec.yaml` file:
> 
> ```yaml
> dependencies:
>   validators: ^1.0.0
> ```

Because my_app depends on validator ^1.0.0 which doesn't match any versions, version solving failed.

**Comment by willladislaw** [comment]
validator: ">=0.0.4 <0.1.0"

The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.

Because my_app depends on validator >=0.0.2 which requires SDK version <2.0.0, version solving failed.


pub get failed (1)

**Comment by luisvt** [comment]
@willladislaw you need to upgrade to version `1.0.0` or greater. Previous versions don't support dart-2
